In [126]:
import pandas as pd
import numpy  as np

In [127]:
df = pd.read_csv("../Data/dataset.csv")

In [128]:
df.head(10)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35
6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50
7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20
9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95

In [129]:
# drop the unnecessary columns such as name and Location

df.drop(['Name','Location'], inplace=True, axis=1)

In [130]:
df.head(10)

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
5,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35
6,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50
7,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
8,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20
9,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95

here we first of all extract the numerical values from the categorical features

In [131]:
df['Mileage'] = df['Mileage'].str.extract(r'(\d+\.?\d*)')
df['Engine'] = df['Engine'].str.extract(r'(\d+)')
df['Power'] = df['Power'].str.extract(r'(\d+\.?\d*)')

In [132]:
df.head()

,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0,NaN,1.75
1,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,NaN,12.50
2,2011,46000,Petrol,Manual,First,18.2,1199,88.7,5.0,8.61 Lakh,4.50
3,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,NaN,6.00
4,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,NaN,17.74

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   object
 3   Transmission       6019 non-null   object
 4   Owner_Type         6019 non-null   object
 5   Mileage            6017 non-null   object
 6   Engine             5983 non-null   object
 7   Power              5876 non-null   object
 8   Seats              5977 non-null   float64
 9   New_Price          824 non-null    object
 10  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 517.4+ KB

In [134]:
## ee extract cheytha number stringil ninne or objectil ninne floatilot aakanam

df['Mileage'] = pd.to_numeric(df['Mileage'])
df['Engine'] = pd.to_numeric(df['Engine'])
df['Power'] = pd.to_numeric(df['Power'])

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   object
 3   Transmission       6019 non-null   object
 4   Owner_Type         6019 non-null   object
 5   Mileage            6017 non-null   float64
 6   Engine             5983 non-null   float64
 7   Power              5876 non-null   float64
 8   Seats              5977 non-null   float64
 9   New_Price          824 non-null    object
 10  Price              6019 non-null   float64
dtypes: float64(5), int64(2), object(4)
memory usage: 517.4+ KB

In [136]:
df['New_Price'] = df['New_Price'].str.extract(r'(\d+\.?\d*)')
df["New_Price"] = pd.to_numeric(df['New_Price'])

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   object
 3   Transmission       6019 non-null   object
 4   Owner_Type         6019 non-null   object
 5   Mileage            6017 non-null   float64
 6   Engine             5983 non-null   float64
 7   Power              5876 non-null   float64
 8   Seats              5977 non-null   float64
 9   New_Price          824 non-null    float64
 10  Price              6019 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 517.4+ KB

In [138]:
# In this categorical features the Owner_type has an natural order and other two should be handled by One hot encoding because
# they have mutual order

In [139]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\usedcarprice\env\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in d:\usedcarprice\env\lib\site-packages (from scikit-learn) (2.2.5)
Requirement already satisfied: scipy>=1.6.0 in d:\usedcarprice\env\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in d:\usedcarprice\env\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\usedcarprice\env\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               6019 non-null   int64
 1   Kilometers_Driven  6019 non-null   int64
 2   Fuel_Type          6019 non-null   object
 3   Transmission       6019 non-null   object
 4   Owner_Type         6019 non-null   object
 5   Mileage            6017 non-null   float64
 6   Engine             5983 non-null   float64
 7   Power              5876 non-null   float64
 8   Seats              5977 non-null   float64
 9   New_Price          824 non-null    float64
 10  Price              6019 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 517.4+ KB

In [141]:
## now only New_Price, and other features is to be handled we use SimpleImputer to handle this issue 
## and to avoid train test contamination lets use pipleline technique 
## so to add the numerical preprocessing steps to the pipeline and at last the model is also bundled to the pipleline
## before the we need to perform the traintestsplit to avoid the contamination and avoid the cheating the model

In [142]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [143]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Price'], axis=1), df.Price, test_size=.2, random_state=0)

In [144]:
X_train.shape

(4815, 10)

In [145]:
## after this we use imputer to fill the missing columns
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4815 entries, 3509 to 2732
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               4815 non-null   int64
 1   Kilometers_Driven  4815 non-null   int64
 2   Fuel_Type          4815 non-null   object
 3   Transmission       4815 non-null   object
 4   Owner_Type         4815 non-null   object
 5   Mileage            4814 non-null   float64
 6   Engine             4790 non-null   float64
 7   Power              4702 non-null   float64
 8   Seats              4785 non-null   float64
 9   New_Price          660 non-null    float64
dtypes: float64(5), int64(2), object(3)
memory usage: 413.8+ KB

In [146]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 4815 entries, 3509 to 2732
Series name: Price
Non-Null Count  Dtype
--------------  -----
4815 non-null   float64
dtypes: float64(1)
memory usage: 75.2 KB

In [147]:
## extracting different types of features from X_train set to categories the pipeline needed
## from the above set we can understand the owner_type has an inherent nature so we use ordial encoding
## rest of the categorical variable goes under onehotencoding

num_features = X_train.select_dtypes(exclude=['object']).columns.tolist()
label_cat_features = X_train.select_dtypes(include=['object']).columns.tolist()
ordinal_cat_features = list()
ordinal_cat_features.append(label_cat_features.pop())

In [148]:
ordinal_cat_features, num_features, label_cat_features

(['Owner_Type'],
 ['Year',
  'Kilometers_Driven',
  'Mileage',
  'Engine',
  'Power',
  'Seats',
  'New_Price'],
 ['Fuel_Type', 'Transmission'])

In [149]:
## missing values features are [mileage, engine, power , seats, new_Price]
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.feature_selection import SelectKBest, f_regression

#since we have only numerical features we are bundling numerical preprocessing only
num_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer()),
        ("scaler", StandardScaler()),
        ("feature_selection", SelectKBest(score_func=f_regression, k='all'))
    ]
)

ordinal_order = [['First','Second', 'Third', 'Fourth & Above']]

ordinal_transformer = Pipeline(
    steps=[
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("encoder", OrdinalEncoder(categories=ordinal_order))
    ] 
)

label_transformer = Pipeline(
    steps=[
        ("imput", SimpleImputer(strategy="most_frequent")),
        ("encode", OneHotEncoder(sparse_output=False, handle_unknown="ignore"))
    ]
)

In [150]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_transformer, num_features),
        ('ordinal', ordinal_transformer, ordinal_cat_features),
        ('label', label_transformer, label_cat_features)
    ]
)

In [151]:
!pip install xgboost

Requirement already satisfied: xgboost in d:\usedcarprice\env\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in d:\usedcarprice\env\lib\site-packages (from xgboost) (2.2.5)
Requirement already satisfied: scipy in d:\usedcarprice\env\lib\site-packages (from xgboost) (1.15.2)

[notice] A new release of pip is available: 24.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [152]:
## define various models and select the best one according to the r2score
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(n_estimators=200, random_state = 0),
    'Decision Tree': DecisionTreeRegressor(random_state = 0),
    'KNeighborsRegressor' : KNeighborsRegressor(),
    'XGBoost': XGBRegressor()
}

In [153]:
## find the best model by cross validation by keeping cv = 5
from sklearn.model_selection import cross_val_score
for name, model in models.items():
    pipeline = Pipeline(steps =[
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    score = cross_val_score(pipeline, X_train, y_train, cv=5, scoring="r2")
    print(f"{name} has {np.round(score.mean(), 4)} of Average r2 score")

Linear Regression has 0.6433 of Average r2 score
Random Forest has 0.8681 of Average r2 score
Decision Tree has 0.7326 of Average r2 score
KNeighborsRegressor has 0.8526 of Average r2 score
XGBoost has 0.8567 of Average r2 score

In [154]:

## bundle preprocessing and the best model together
## from the above observation Random forest has the highest accuracy so we consider that model
pipeline = Pipeline(
    steps=[
        ("col", preprocessor),
        ("model", RandomForestRegressor(n_estimators=200, random_state = 0))
    ]
)

In [155]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('col',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler()),
                                                                  ('feature_selection',
                                                                   SelectKBest(k='all',
                                                                               score_func=<function f_regression at 0x000001FC83EFB100>))]),
                                                  ['Year', 'Kilometers_Driven',
                                                   'Mileage', 'Engine', 'Power',
                                                   'Seats', 'New_Price']),
                                                 ('ordinal',
                                                  Pipeline(steps=[('impute',
                                                                   Sim...
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['First',
                                                                                               'Second',
                                                                                               'Third',
                                                                                               'Fourth '
                                                                                               '& '
                                                                                               'Above']]))]),
                                                  ['Owner_Type']),
                                                 ('label',
                                                  Pipeline(steps=[('imput',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Fuel_Type',
                                                   'Transmission'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, random_state=0))])

In [156]:
y_hat = pipeline.predict(X_test)
print(y_hat)

[7.90025    3.11975    4.0811     ... 7.82525    5.73524583 3.546     ]

In [157]:
from sklearn.metrics import mean_absolute_error, r2_score

In [158]:
print(mean_absolute_error(y_hat, y_test))

1.605727998899172

In [159]:
print(f"r2score of randomforestregressor is : {np.round(r2_score(y_hat, y_test)*100, 4)}")

r2score of randomforestregressor is : 89.4906

In [160]:
X_full  = pd.concat([X_train, X_test], axis = 0)
y_full = pd.concat([y_train, y_test], axis = 0)

In [161]:
pipeline.fit(X_full, y_full)

Pipeline(steps=[('col',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler()),
                                                                  ('feature_selection',
                                                                   SelectKBest(k='all',
                                                                               score_func=<function f_regression at 0x000001FC83EFB100>))]),
                                                  ['Year', 'Kilometers_Driven',
                                                   'Mileage', 'Engine', 'Power',
                                                   'Seats', 'New_Price']),
                                                 ('ordinal',
                                                  Pipeline(steps=[('impute',
                                                                   Sim...
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['First',
                                                                                               'Second',
                                                                                               'Third',
                                                                                               'Fourth '
                                                                                               '& '
                                                                                               'Above']]))]),
                                                  ['Owner_Type']),
                                                 ('label',
                                                  Pipeline(steps=[('imput',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Fuel_Type',
                                                   'Transmission'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, random_state=0))])

In [162]:
#finally dump the model

In [123]:
## It is trained on full dataset so here the model is not overfitted

In [124]:
import joblib

In [125]:
joblib.dump(pipeline, "../model/Model.pkl")

['../model/Model.pkl']